### ISSUE TITLE
panic: open discvx/prefixmap.go: no such file or directory

### ISSUE THREAD

**Issue by bayareaunicorn** [dennis-tra/nebula#60] opened 2024-04-08 11:25 UTC
System: Apple M1 Silicon

```
panic: open discvx/prefixmap.go: no such file or directory

goroutine 1 [running]:
main.main()
	/home/runner/work/nebula/nebula/gen.go:64 +0x590

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

[nebula_Darwin_arm64.tar.gz](https://github.com/dennis-tra/nebula/releases/download/2.2.0/nebula_Darwin_arm64.tar.gz)

**Comment by dark982** [comment] 2024-04-25 11:46
Also on ubuntu 23 
Release 2.2.0

**Comment by dennis-tra** [comment] 2024-05-01 18:24
Sorry for the late reply. I'm currently on vacation 👍 

Are you actually trying to regenerate the prefix map? Unfortunately, I can't reproduce your issue. I'm also on an M1 Mac. I did a fresh clone and ran `go run gen.go`:

```
git clone https://github.com/dennis-tra/nebula
go run gen.go
```

If you're actually interested in running Nebula, then you would need to run the `main` package in `./cmd/nebula/`.

To better be able to reproduce your issue, could you send me the command that you have tried to run?

**Comment by cortze** [comment] 2024-05-02 13:54
Is there anything I should check here @dennis-tra ?
More than happy to try things out on x86 arch, when more info is given :)

**Comment by dennis-tra** [comment] 2024-05-02 14:40
I guess just a repro would be great. Do you run into the same issue?

**Comment by cortze** [comment] 2024-05-02 16:11
I could reproduce the error downloading the latest release (v2.2.0):
```
./nebula --dry-run crawl --limit 100
breaking prefixes...
writing prefixes...
panic: open discvx/prefixmap.go: no such file or directory

goroutine 1 [running]:
main.main()
        /home/runner/work/nebula/nebula/gen.go:64 +0x625
```

However, building it manually, I could run both:
- (successfully) `go run gen.go`
```shell
$go1.19.13 run gen.go
breaking prefixes...
writing prefixes...
done
```
- (successfully) building the tool manually using `go1.19.13` using the Makefile, and run `nebula --dry-run crawl` (I stopped it)
```shell
INFO[0091] Finished crawl                                crawlDuration=1m31.57543725s crawledPeers=11036 dialablePeers=6876 undialablePeers=4160
INFO[0091] Stopped Nebula crawler.
```

**Comment by cortze** [comment] 2024-05-03 11:09
Just FYI, I could trace down the GitHub Actions of the `2.2.0` release. But I couldn't see any problem with the latest manual run of `goreleaser`.

However, it does look like the first time it ran, it had a similar problem with the `GoReleaser@v5` step with the `go generate` command.

Could this be a problem related to that first failed release?

Should I try to generate a new `v2.2.1` release, including updated Polkadot bootstrap nodes, to see if the problem persists?

**Comment by bayareaunicorn** [comment] 2024-05-06 17:09
OS: Mac Air Silicon M1
Go Version: 1.22.2




```
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.33.1/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
make: *** [build] Error 1

```

**Comment by cortze** [comment] 2024-05-06 17:35
Reopening the Issue as `gorelease` isn't happy yet, and it was automatically closed with #62

**Comment by bayareaunicorn** [comment] 2024-05-06 22:43
` make build`
```
fatal: No names found, cannot describe anything.
go build -ldflags "-X main.version= -X main.commit=68fa3bd -X main.date=2024-05-06T15:20:28Z -X main.builtBy=scott" -o dist/nebula github.com/dennis-tra/nebula-crawler/cmd/nebula
go: downloading github.com/quic-go/qtls-go1-19 v0.3.3
# github.com/dennis-tra/nebula-crawler/cmd/nebula
ld: warning: '/private/var/folders/sy/6jq7pfcs1b74qy7jbxqbc1rc0000gn/T/go-link-725967350/go.o' has malformed LC_DYSYMTAB, expected 125 undefined symbols to start at index 61364, found 257 undefined symbols starting at index 128
```

**Comment by dennis-tra** [comment] 2024-05-07 08:13
Hi @bayareaunicorn, apologies for the surprisingly complicated build process. Thanks for bearing with us here.

The error `fatal: No names found, cannot describe anything.` comes from `git describe --tags --abbrev=0` not finding any recent tags. The most recent tag is used as an ldflag when you build Nebula. In your case, the repository doesn't seem to contain any tags which is surprising.

May I ask how you have cloned the repo? Just a regular `git clone ...` would have pulled the tags.

Anyway, I'll fix the Makefile to cover the case where no tags are present. In the meantime, you can also run the command that's run by `make build` under the hood yourself (without all the ldflags):

```
go build -o dist/nebula github.com/dennis-tra/nebula-crawler/cmd/nebula
```

**Comment by cortze** [comment] 2024-05-08 16:28
Finally made `goreleaser` [to work](https://github.com/dennis-tra/nebula/actions/runs/9005111385/job/24739677153)
Could any of you try out the `darwin` releases from the [`2.2.1` tag](https://github.com/dennis-tra/nebula/releases/tag/2.2.1) ?

**Comment by cortze** [comment] 2024-05-13 08:05
Closing this issue as #68 finally fixed the cross-compilation of binary at GitHub actions

**Closed by cortze** 2024-05-13 08:05 UTC
